# znuzhgfw/core/report.py
from __future__ import annotations

from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Literal

from .report_html import render_html_report


# -----------------------------------------
# Severity Literal
# -----------------------------------------
Severity = Literal["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


# -----------------------------------------
# Finding Object
# -----------------------------------------
@dataclass
class Finding:
    id: int
    title: str
    severity: Severity
    url: str = ""
    detail: str = ""
    category: str | None = None
    scanner: str | None = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# -----------------------------------------
# Summary Builder
# -----------------------------------------
def build_summary(findings: List[Finding]) -> Dict[str, Any]:
    by_sev: Dict[str, int] = {
        "CRITICAL": 0,
        "HIGH": 0,
        "MEDIUM": 0,
        "LOW": 0,
        "INFO": 0,
    }

    for f in findings:
        s = f.severity.upper()
        if s not in by_sev:
            by_sev["INFO"] += 1
        else:
            by_sev[s] += 1

    return {
        "total": len(findings),
        "by_severity": by_sev,
    }


# -----------------------------------------
# Markdown Renderer
# -----------------------------------------
def render_markdown_report(
    target: str,
    summary: Dict[str, Any],
    findings: List[Finding],
    generated_at: datetime | None = None,
) -> str:

    generated_at = generated_at or datetime.utcnow()
    lines: List[str] = []

    lines.append("# ZNUZHG Pentest Report\n")
    lines.append(f"**Target:** `{target}`\n")
    lines.append(f"**Generated at:** {generated_at.isoformat()} UTC\n")

    # Summary
    lines.append("## Summary\n")
    lines.append(f"- **Total findings:** {summary['total']}\n")
    lines.append("### By Severity")

    for sev, count in summary["by_severity"].items():
        lines.append(f"- **{sev}**: {count}")
    lines.append("\n---\n")

    # Findings
    lines.append("## Findings\n")

    if not findings:
        lines.append("_No findings recorded._")
    else:
        for f in findings:
            lines.append(f"### #{f.id} — {f.title}")
            lines.append(f"- **Severity:** {f.severity}")
            if f.url:
                lines.append(f"- **URL:** `{f.url}`")
            if f.category:
                lines.append(f"- **Category:** `{f.category}`")
            if f.scanner:
                lines.append(f"- **Scanner:** `{f.scanner}`")
            lines.append("")

            if f.detail:
                lines.append("```text")
                lines.append(f.detail)
                lines.append("```")
            lines.append("")

    lines.append("---")
    lines.append(
        "> Generated by **ZNUZHGFW**. Use only on systems where you have explicit permission.\n"
    )

    return "\n".join(lines)


# -----------------------------------------
# JSON Renderer
# -----------------------------------------
def render_json_report(
    target: str,
    summary: Dict[str, Any],
    findings: List[Finding],
    generated_at: datetime | None = None,
) -> str:

    import json

    generated_at = generated_at or datetime.utcnow()

    data = {
        "target": target,
        "generated_at": generated_at.isoformat() + "Z",
        "summary": summary,
        "findings": [f.to_dict() for f in findings],
    }

    return json.dumps(data, indent=2, ensure_ascii=False)


# -----------------------------------------
# CENTRAL REPORT WRITER
# -----------------------------------------
def write_report(
    path: str | Path,
    target: str,
    findings: List[Finding],
    fmt: Literal["html", "markdown", "md", "json"] = "html",
) -> Path:

    path = Path(path)
    summary = build_summary(findings)
    generated_at = datetime.utcnow()
    fmt_norm = fmt.lower()

    if fmt_norm in ("md", "markdown"):
        content = render_markdown_report(target, summary, findings, generated_at)
    elif fmt_norm == "json":
        content = render_json_report(target, summary, findings, generated_at)
    elif fmt_norm == "html":
        payload = [f.to_dict() for f in findings]
        content = render_html_report(target, summary, payload, generated_at)
    else:
        raise ValueError(f"Unknown report format: {fmt}")

    path.write_text(content, encoding="utf-8")
    return path


# ============================================================
# REPORT CLASS (FINAL VERSION)
# ============================================================
class Report:
    """
    Fully-compatible ZNUZHGFW Report Collector.
    Scanner'lar bulguyu buraya ekler.
    En sonunda HTML / JSON / MD raporu yazdırabilir.
    """

    def __init__(self, target: str):
        self.target = target
        self.findings: List[Finding] = []
        self._counter = 1

    # ---- Add Finding ----
    def add(
        self,
        *,
        severity: Severity = "INFO",
        title: str = "",
        url: str = "",
        detail: str = "",
        category: str | None = None,
        scanner: str | None = None,
    ):
        f = Finding(
            id=self._counter,
            title=title or "Untitled Finding",
            severity=severity.upper(),
            url=url,
            detail=detail,
            category=category,
            scanner=scanner,
        )
        self.findings.append(f)
        self._counter += 1

    # ---- Writers ----
    def write_html(self, path: str | Path):
        summary = build_summary(self.findings)
        payload = [f.to_dict() for f in self.findings]
        out = render_html_report(self.target, summary, payload, datetime.utcnow())
        p = Path(path)
        p.write_text(out, encoding="utf-8")
        return p

    def write_markdown(self, path: str | Path):
        summary = build_summary(self.findings)
        out = render_markdown_report(
            self.target, summary, self.findings, datetime.utcnow()
        )
        p = Path(path)
        p.write_text(out, encoding="utf-8")
        return p

    def write_json(self, path: str | Path):
        summary = build_summary(self.findings)
        out = render_json_report(
            self.target, summary, self.findings, datetime.utcnow()
        )
        p = Path(path)
        p.write_text(out, encoding="utf-8")
        return p
